package:
  name: sls_detector_lib
  version: 3.1.3


source:
  git_rev: 3.1.3
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake
    - pyzmq

  host:
    - libstdcxx-ng
    - libgcc-ng
    - pyzmq

  run:
    - pyzmq
    - libstdcxx-ng
    - libgcc-ng



about:
  home: no
  license: GPL2

