package:
  name: sls_detector_lib
  version: "3.1.1"


source:
  git_rev: 3.1.1
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 0
  run_exports:
   - libstdc++  {{ pin_compatible('g++', 'x') }}

requirements:
  build:
    - gcc_linux-64
    - libgcc
    - cmake
    - libgcc
    - pyzmq
    
  run:
    - numpy
    - libgcc
    - pyzmq

about:
  home: no
  license: GPL2
