package:
  name: sls_detector_lib
  version: "compiler"


source:
  git_rev: developer
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake

  host:
    - libstdcxx-ng
    - libgcc-ng

  run:
    - pyzmq
    - libstdcxx-ng
    - libgcc-ng



about:
  home: no
  license: GPL2

