package:
  name: sls_detector_lib
  version: "developer"


source:
  git_rev: developer
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 0
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  build:
    - {{ compiler('c') }}       
    - {{ compiler('cxx') }}  
    - cmake
    - libpng
    - pyzmq
    - zlib
  
    host:
    - zlib
    - libpng


  run:
    - pyzmq
    - libpng
    - libstdcxx-ng
    - libgcc-ng


about:
  home: no
  license: GPL2

