package:
  name: sls_detector_lib
  version: "3.1.1"


source:
  git_rev: 3.1.1
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 1

requirements:
  build:
    - gcc_linux-64
    - gxx_linux-64
    - libgcc-ng 
    - libstdcxx-ng
    - pyzmq
    
  run:
    - numpy
    - libstdcxx-ng
    - libgcc-ng 
    - pyzmq

about:
  home: no
  license: GPL2
