package:
  name: sls_detector_lib
  version: "developer"


source:
  git_rev: developer
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    # - gcc_linux-64
    # - gxx_linux-64
    # - libstdcxx-ng
    # - libgcc-ng
    - cmake
    - gcc
    - libgcc
    - libpng >=1.6.32,<1.6.35
    # - pyzmq
    # - zlib

  
  # host:
  #   - zlib
  #   - libpng >=1.6.32,<1.6.35


  run:
    - pyzmq
    - libpng >=1.6.32,<1.6.35
    - libgcc
    # - libstdcxx-ng
    # - libgcc-ng
    # - zlib


about:
  home: no
  license: GPL2

