package:
  name: sls_detector_lib
  version: "developer"


source:
  git_rev: developer
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - cmake
    - gcc
    - libstdcxx-ng
    - libgcc-ng
    - libpng >=1.6.32,<1.6.35
    # - pyzmq
    # - zlib



  run:
    - pyzmq
    - libpng >=1.6.32,<1.6.35
    - libstdcxx-ng
    - libgcc-ng



about:
  home: no
  license: GPL2

