package:
  name: sls_detector_lib
  version: "developer"


source:
  git_rev: developer
  git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git

build:
  number: 0

requirements:
  build:
    - gcc_linux-64
    - gxx_linux-64
    - libstdcxx-ng
    - pyzmq
    
  run:
    - numpy
    - libstdcxx-ng
    - pyzmq

about:
  home: no
  license: GPL2
